// Curated anime presets for quick selection
export const ANIME_PRESETS = {
  ecchi: {
    name: "Ecchi / Harem",
    description: "For those who appreciate... culture",
    animes: [
      "High School DxD",
      "To Love-Ru",
      "Date A Live",
      "Sekirei",
      "Rosario + Vampire",
      "Infinite Stratos",
      "The Testament of Sister New Devil",
      "Campione!",
      "Trinity Seven",
      "Freezing",
      "My Dress-Up Darling",
      "Rent-a-Girlfriend",
    ],
  },
  shonen: {
    name: "Shonen Classics",
    description: "The big 3 and beyond",
    animes: [
      "Naruto",
      "Naruto Shippuden",
      "Bleach",
      "One Piece",
      "Dragon Ball Z",
      "Fairy Tail",
      "Hunter x Hunter",
      "Soul Eater",
      "Fullmetal Alchemist: Brotherhood",
      "Katekyo Hitman Reborn!",
      "My Hero Academia",
      "Black Clover",
      "Fire Force",
      "The Seven Deadly Sins",
      "Chainsaw Man",
      "Blue Exorcist",
      "Tokyo Ghoul",
    ],
  },
  fate: {
    name: "Fate Series",
    description: "Servants and masters",
    animes: [
      "Fate/stay night",
      "Fate/stay night [Unlimited Blade Works]",
      "Fate/stay night [Heaven's Feel] I. presage flower",
      "Fate/Zero",
      "Fate/Apocrypha",
      "Fate/Grand Order -Absolute Demonic Front: Babylonia-",
      "Fate/Grand Order - Divine Realm of the Round Table: Camelot",
      "Fate/Grand Order: First Order",
      "Fate/Extra Last Encore",
      "Fate/kaleid liner Prisma Illya",
      "Lord El-Melloi II's Case Files {Rail Zeppelin} Grace note",
      "Fate/strange Fake: Whispers of Dawn",
      "Today's Menu for the Emiya Family",
      "Carnival Phantasm",
    ],
  },
  romance: {
    name: "Romance / Romcom",
    description: "Waifus and husbandos",
    animes: [
      "The Quintessential Quintuplets",
      "My Dress-Up Darling",
      "Rent-a-Girlfriend",
      "Toradora!",
      "Nisekoi",
      "Saekano: How to Raise a Boring Girlfriend",
      "My Teen Romantic Comedy SNAFU",
      "Rascal Does Not Dream of Bunny Girl Senpai",
      "Love Live! School idol project",
      "Classroom of the Elite",
      "Darling in the FranXX",
    ],
  },
  monogatari: {
    name: "Monogatari Series",
    description: "Head tilts and dialogue",
    animes: [
      "Bakemonogatari",
      "Kizumonogatari Part 1: Tekketsu",
      "Nisemonogatari",
      "Nekomonogatari (Black)",
      "Monogatari Series: Second Season",
      "Hanamonogatari",
      "Tsukimonogatari",
      "Owarimonogatari",
      "Koyomimonogatari",
      "Kizumonogatari",
      "Zoku Owarimonogatari",
    ],
  },
  action: {
    name: "Action / Dark",
    description: "Edgy and intense",
    animes: [
      "Akame ga Kill!",
      "Kill la Kill",
      "Gurren Lagann",
      "Attack on Titan",
      "Tokyo Ghoul",
      "Chainsaw Man",
      "Neon Genesis Evangelion",
      "Code Geass",
      "Steins;Gate",
    ],
  },
  isekai: {
    name: "Isekai / Fantasy",
    description: "Another world awaits",
    animes: [
      "Sword Art Online",
      "Re:ZERO -Starting Life in Another World-",
      "No Game No Life",
      "The Seven Deadly Sins",
    ],
  },
} as const;

export type PresetKey = keyof typeof ANIME_PRESETS;

export const ANIMES = [
  // Ecchi / Harem
  "High School DxD",
  "To Love-Ru",
  "Date A Live",
  "Sekirei",
  "Rosario + Vampire",
  "Infinite Stratos",
  "The Testament of Sister New Devil",
  "Campione!",
  "Trinity Seven",
  "Freezing",

  // Shonen / Action Classics
  "Naruto",
  "Naruto Shippuden",
  "Bleach",
  "One Piece",
  "Dragon Ball Z",
  "Fairy Tail",
  "Hunter x Hunter",
  "Soul Eater",
  "Fullmetal Alchemist: Brotherhood",
  "Katekyo Hitman Reborn!",

  // Modern Shonen
  "Jujutsu Kaisen",
  "Demon Slayer: Kimetsu no Yaiba",
  "My Hero Academia",
  "Black Clover",
  "Fire Force",
  "The Seven Deadly Sins",
  "Chainsaw Man",
  "Blue Exorcist",
  "Tokyo Ghoul",

  // Action / Sci-Fi / Fantasy
  "Akame ga Kill!",
  "Kill la Kill",
  "Gurren Lagann",
  "Sword Art Online",
  "Re:ZERO -Starting Life in Another World-",
  "No Game No Life",

  // FATE SERIES
  "Fate/stay night",
  "Fate/stay night [Unlimited Blade Works]",
  "Fate/stay night [Heaven's Feel] I. presage flower",
  "Fate/Zero",
  "Fate/Apocrypha",
  "Fate/Grand Order -Absolute Demonic Front: Babylonia-",
  "Fate/Grand Order - Divine Realm of the Round Table: Camelot",
  "Fate/Grand Order: First Order",
  "Fate/Extra Last Encore",
  "Fate/kaleid liner Prisma Illya",
  "Lord El-Melloi II's Case Files {Rail Zeppelin} Grace note",
  "Fate/strange Fake: Whispers of Dawn",
  "Today's Menu for the Emiya Family",
  "Carnival Phantasm",

  "Steins;Gate",
  "Darling in the FranXX",
  "Code Geass",
  "Neon Genesis Evangelion",
  "Attack on Titan",

  // Romance / Slice of Life
  "The Quintessential Quintuplets",
  "My Dress-Up Darling",
  "Rent-a-Girlfriend",
  "Toradora!",
  "Nisekoi",
  "Saekano: How to Raise a Boring Girlfriend",
  "My Teen Romantic Comedy SNAFU",
  "Rascal Does Not Dream of Bunny Girl Senpai",
  "Love Live! School idol project",
  "Classroom of the Elite",

  // Monogatari Series
  "Bakemonogatari",
  "Kizumonogatari Part 1: Tekketsu",
  "Nisemonogatari",
  "Nekomonogatari (Black)",
  "Monogatari Series: Second Season",
  "Hanamonogatari",
  "Tsukimonogatari",
  "Owarimonogatari",
  "Koyomimonogatari",
  "Kizumonogatari",
  "Zoku Owarimonogatari",
] as const;

export type AnimeName = (typeof ANIMES)[number];

export const GENDERS = [
  "Male",
  "Female",
  "Non-binary",
  "Androgynous",
  "Unknown",
] as const;

export type Gender = (typeof GENDERS)[number];
